/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 ///*////sss
package com.interfaces;

import com.methods.Methods;

/**
 *
 * @author erichaag
 */
public class Oden extends javax.swing.JFrame {

    int v1[], v2[];

    /**
     * Creates new form Oden
     */
    public Oden() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        panel2 = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnAction = new javax.swing.JButton();
        cmb1 = new javax.swing.JComboBox<>();
        btnClean = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos iniciales"));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tamaño vector 2:");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel2.setText("Tamaño vector 1:");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        panel1.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 60, 30));
        panel1.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 60, 30));

        Principal.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 220, 210));

        panel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreate.setText("Crear vector");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        panel2.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 190, -1));

        btnAction.setText("Operar");
        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });
        panel2.add(btnAction, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 190, -1));

        cmb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Llenar Vector 1 Automático", "Llenar Vector 2 Automático", "Llenar Vector 1 Manual", "Llenar Vector 2 Manual", "Promedio Elementos V1", "Mayor Valor V2", "Sumatoria V1", "Productoria V2", "1. Sumatoria", "2. Productoria", "3. Mayor elemento", "4. Menor elemento", "5. Elementos pares", "6. Elementos impares", "7. Elementos primos", "8. Suma de un vector1 y vector2", "9. Resta de un vector1 y vector2", "10. Vector que se reite y diga cual es", "11. Union de dos vectores", "11. Interseccion de los dos conjuntos de vectores", "12. Diferencia de vector 1 con vector2", "13. Diferencia de vector 2 con vector 1" }));
        panel2.add(cmb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 230, -1));

        btnClean.setText("Limpiar");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });
        panel2.add(btnClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 190, -1));

        btnClose.setText("Cerrar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        panel2.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 190, -1));

        Principal.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 270, 210));

        lb1.setText("Vectores");
        Principal.add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        area1.setColumns(20);
        area1.setRows(5);
        jScrollPane1.setViewportView(area1);

        jPanel3.add(jScrollPane1);

        Principal.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 500, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        int tv1, tv2;

        tv1 = Integer.parseInt(txt1.getText());
        tv2 = Integer.parseInt(txt2.getText());

        v1 = new int[tv1];
        v2 = new int[tv2];
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed
        // TODO add your handling code here:
                int op;

        op = cmb1.getSelectedIndex();

        switch (op) {
            case 0:
                area1.append("VECTOR 1 \n");
                v1 = Methods.llenar_automatico(v1);
                area1.append(Methods.mostrar(v1) + "\n");
                break;
            case 1:
                area1.append("VECTOR 2 \n");
                v2 = Methods.llenar_automatico(v2);
                area1.append(Methods.mostrar(v2) + "\n");
                break;
            case 4:
                area1.append("PROMEDIO VECTOR 1 \n");
                area1.append("" + Methods.promedio(v1));
                System.out.println(v1[0]);
                break;
            case 5:
                area1.append("MAYOR VALOR VECTOR 2 \n");
                area1.append("" + Methods.mayor_valor(v2));
                break;

        }


    }//GEN-LAST:event_btnActionActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        // TODO add your handling code here:
        limiar_e();
    }//GEN-LAST:event_btnCleanActionPerformed

    
    public void limiar_e(){
        txt1.setText(null);
        txt2.setText(null);
        area1.setText(null);
        cmb1.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Oden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Oden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Oden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Oden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Oden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Principal;
    private javax.swing.JTextArea area1;
    private javax.swing.JButton btnAction;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox<String> cmb1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
